- examples/custom-scripts/NetBox_DNS_Exporter.py
- pyproject.toml
This PR raises the minimum version of the pytest library to 7.2 and sets the Jinja 2 environment in one of the sample scripts to use `autoescape=True`.
> Handled security warnings by GitHub

- netbox_dns/api/serializers.py
> Set `allow_null` to `True` for some non-required API fields

- docs/using_netbox_dns.md
- netbox_dns/__init__.py
- netbox_dns/models.py
- netbox_dns/tests/record/test_uniqueness.py
fixes #38
This PR creates a new configuration option `enforce_unique_records` (disabled by default) that inhibits the addition of RRs to a zone when an active RR with the same name, type and value already exists.
> Add a new configuration option to enforce unique records

- netbox_dns/tests/record/test_name_validation.py
- netbox_dns/validators.py
fixes #45
PTR records having wildcard values did not validate as legal FQDN.
This went unnoticed because the tests did not create PTR records. Fixed the tests and the issue.
> Fix hostname validation for PTR records with wildcard targets

- netbox_dns/__init__.py
- netbox_dns/models.py
- netbox_dns/template_content.py
- netbox_dns/utilities.py
- netbox_dns/validators.py
Set minimum NetBox version to 3.5.8 to avoid installing on lower versions
> Fixed import statements for NetBox 3.5.8

- netbox_dns/models.py
- netbox_dns/tests/zone/test_rname_validation.py
> Added validation to the SOA RNAME field

- netbox_dns/migrations/0024_tenancy.py
Migration `netbox_dns.0024_tenancy` was created by `makemigrations` with a dependency on `tenancy.0011_contactassignment_tags`.
Unfortunately, that migration was only introduced with NetBox 3.6.0, so the dependency breaks compatibility with 3.5.x (> 3.5.8). This PR changes the dependency so NetBox 3.5 should be properly supported again.
> Fixed migration dependency for NetBox 3.5.x

- netbox_dns/models.py
- netbox_dns/tests/record/test_uniqueness.py
> Check the type of a record when testing for uniqueness

- netbox_dns/__init__.py
- netbox_dns/models.py
- netbox_dns/tests/test_netbox_dns.py
- pyproject.toml
When a record is edited, the title of the record form is set to a version with interpreted IDN characters. This requires parsing the title using `dnspython`. When a record is edited and the edit results in a record name not conforming to DNS naming standards, this conversion fails.
fixes #81
> Shorten DNS names when creating record string representation

- netbox_dns/__init__.py
There are multiple problems causing this:
* The check for the feature enable status is done against the default settings, not the current settings of NetBox DNS. In the default settings, the feature is turned off, so the check code is never executed.
* Logging is done against the `logging` instance `netbox.config`, which is not defined by default, so the log message wouldn't have appeared anywhere by default.
The new code writes the warning message to `STDOUT`, so it can be seen more easily.
fixes #84
> Fix the startup warning for missing custom fields

- README.md
- docs/using_netbox_dns.md
- netbox_dns/__init__.py
- netbox_dns/middleware.py
- netbox_dns/models/record.py
- netbox_dns/models/zone.py
- netbox_dns/template_content.py
- netbox_dns/utilities.py
- netbox_dns/validators.py
fixes #94
This is not exactly an example of beautiful code, but it solves the compatibility problem with all 3.5.x NetBox releases, so it is the lesser evil than unnecessarily imposing version restrictions.
> Restored compatibility with NetBox < 3.5.8

- netbox_dns/tests/record/test_name_validation.py
- netbox_dns/validators.py
fixes #106
This fixes an issue where `tolerate_underscores_in_hostnames` works for all RR types except the ones for which leading underscores are allowed.
> Tolerate underscores even if leading underscores are allowed

- netbox_dns/filters/nameserver.py
- netbox_dns/forms/nameserver.py
- netbox_dns/forms/record.py
- netbox_dns/forms/view.py
- netbox_dns/forms/zone.py
- netbox_dns/tables/view.py
fixes #110
Fixed a very, very old bug, back from the days of `netbox-dns` (and painstakingly ported forward for a while).
`Zone`, `NameServer`, `Record` and `View` allowed tags to be set from the very beginning, but tags have never been importable. This is fixed now.
While I was at it, I fixed some other tag-related quirks as well.
> Fixed bulk import of Zone, Record, View and NameServer with tags

- netbox_dns/template_content.py
- netbox_dns/templates/netbox_dns/record/related.html
This PR contains a feature that makes it possible to show related DNS address or pointer records for an `IPAddress` object.
Note that all DNS records that match the IP address will be displayed, whether they are actually related to that IP address or not. Records could be in different views or relate to the same IP address in a different VRF, which cannot be determined without the IPAM coupling feature.
The feature can be enabled using the `feature_ipam_dns_info` configuration flag in `configuration.py`.
> Experimental Feature: Related DNS records for IP Addresses without IPAM Coupling

- netbox_dns/template_content.py
> Do not display the "Related DNS Objects" pane for tenanty under NetBox 3.7.0

- netbox_dns/migrations/0026_domain_registration.py
A `makemigrations` run done after NetBox 3.6.0 broke compatibility with NetBox 3.5.x. Fixed that by referencing an older NetBox migration as a dependency.
> Fixed migration dependency with NetBox < 3.6.0

- netbox_dns/signals/ipam_coupling.py
fixes #141
Before working with the data supplied by the `clean()` method of `ipam.IPAddress`, check if the data supplied is valid.
> Fix post_clean signal handler for ipam.IPAddress

- docs/using_netbox_dns.md
- netbox_dns/tests/ipam_coupling/test_records.py
- netbox_dns/utilities/ipam_coupling.py
fixes #144
This PR adds a new configuration variable `ipam_coupling_ip_active_status_list` that can be used to define the list of statuses for IP addresses that are considered active by the IPAM coupling feature.
Address records for active IP addresses will be created in 'Active' state, while those for IP addresses with other statuses will be created in 'Inactive' state. The new configuration option makes it possible to use unorthodox or custom values for the status of an IP address and still create active address records for it.
This feature was inspired by @bitcollector1 in #140.
> Make the IP address statuses considered active configurable

- netbox_dns/utilities/ipam_coupling.py
fixes #147
If a form returns `None` for the `ipaddress_dns_record_disable_ptr` custom field, the resulting value for `disable_ptr` is `None`, not `False`. This results in an error with the bulk import form.
> Fixed default value if disable_ptr is None

- docs/using_netbox_dns.md
fixes #150 
Documentation had `allow_underscores_in_hostnames` for the option name `tolerate_underscores_in_hostnames`.
> Documentation: Fixed wrong option name

- netbox_dns/api/nested_serializers.py
For some reason yet unknown, `NestedZoneSerializer` does not return the `active` annotation when `many=False` is set. That affects zone serialization for records (`zone`) and zones (`rfc2317_parent_zone`), where `active` is always returned as `None`.
This workaround fixes the problem by overriding `to_representation()` for the serializer and explicitly setting `active`.
fixes #132
> Workaround for NestedZoneSerializer "active=None" issue

- netbox_dns/models/zone.py
- netbox_dns/tests/rfc2317/test_records.py
fixes #155
Compile a set of all CNAMEs to delete instead of looping over PTR records which results in duplicate attempts to delete the same CNAME.
> Fixed deleting RFC2317 zone with multiple records of the same name

- netbox_dns/models/record.py
- netbox_dns/tests/rfc2317/test_records.py
> Handle changing the prefix for RFC2317 zones with duplicate names properly

- netbox_dns/models/record.py
- netbox_dns/tests/record/test_name_validation.py
- netbox_dns/tests/record/test_normalization.py
> Relativise record names to zone name

- netbox_dns/signals/ipam_coupling.py
- netbox_dns/tests/ipam_coupling/test_records.py
> Do not clear DNS name if no coupled DNS record has been set

- netbox_dns/signals/ipam_coupling.py
- netbox_dns/tests/ipam_coupling/test_api.py
This is a possible solution to issue #166.
In web UI or API context, the coupled record is immediately saved when the "post_clean" signal is called. All record creation/modification happen in a transaction, so that object permissions are enforced.
To complete the coupling, the "ipam_ip_address" field must be updated to reference the IP Address. It can't be done at this this point because the IP address is not created yet. It's actually done at the very end, when "post_save" is called. At record creation/modification time, we monkeypatch the "request" object to hold the necessary informations into a "post_save_ops" attribute.
On another note, the semantic of a permission for record modification was not well defined. Two permission checks are done:
- on the current record,
- on the modified …
> Enforce object permissions on coupled DNS record

- netbox_dns/forms/zone.py
- netbox_dns/templates/netbox_dns/zone.html
fixes #194
There were two issues: First was that the form had `soa_serial_auto` as a `BooleanField`, not a `NullBooleanField`, which made it default to `False`. That makes creating a proper logic for `True`/`False`/`None` field options impossible.
The other issue was that consequentially the logic for setting SOA Serial Auto and SOA Serial was broken :-)
> Fixed SOA Serial Auto behaviour with bulk imports

- netbox_dns/models/record.py
- netbox_dns/models/zone.py
- netbox_dns/tests/zone/test_auto_soa_serial.py
fixes #197
This PR addresses the problem of excessive `save()` operations for `Zone` objects on multiple levels.
The main remedy is to introduce a volatile `soa_serial_dirty` attribute for zones, which can be set by other methods when the serial number of a zone needs to be increased, but not saved. This makes it possible for bulk operations on records to make sure that a zone's SOA Serial number will be updated, but without hitting the database.
This feature is then used throughout the `Zone` and `Record` models to determine if and when a `Zone` object needs to be updated immediately (including the generation of a new version of the SOA record), and when it is OK to defer this operation. This is a surprisingly non-trivial decision.
To support this new functionality and ensure that the …
> Reduce the number of `save()` operations when a `Zone` object is saved

- netbox_dns/management/commands/cleanup_rrset_ttl.py
- netbox_dns/models/record.py
- netbox_dns/tests/record/test_uniqueness.py
fixes #210
This PR results in managed `PTR` records being excluded from the check for and enforcement of unique TTLs across RRSets. For further discussion, see #209.
> Do not enforce unique RRSet TTL for managed PTR records

- netbox_dns/models/record.py
- netbox_dns/tests/rfc2317/test_records.py
> Update the TTL for RFC2317 CNAME records in managed parent zones

- netbox_dns/__init__.py
The `ready()` method doesn't provide any real functionality except writing a warning to the log if the custom fields are missing. 
As it makes problems with later versions of NetBox and will be dropped with NetBox version 4.0 anyway, it's no problem to remove it now.
fixes #218
> Removed the ready() method

- netbox_dns/tables/record.py
At some point it looked like a good idea to list the zone first, then the record name.
While in theory this makes sense, it leads to people clicking on the zone name instead of the record name over and over again because the zone name comes first in the table rows. Time to end that confusion ...
> Swap the order of name and zone in Record tables

- docs/using_netbox_dns.md
- netbox_dns/models/record.py
fixes #239
This PR (finally) adds the FQDN to the NetBox global search index.
The index for NetBox DNS must be rebuilt after this update. For this, run the management command
```bash
/opt/netbox/netbox/manage.py reindex netbox_dns
```
A restart is not necessary after re-indexing.
> Added FQDN to global search

- netbox_dns/models/nameserver.py
- netbox_dns/models/record.py
fixes #248
The `post_clean()` signal is a NetBox custom signal and not a Django standard signal, and it is explicitly triggered by running the `super().clean()` method in custom clean() methods.
The `clean()` methods for `Record` and `NameServer` did not call that method, so validators were not run.
> Run `super().clean()` in custom `clean()` methods

- netbox_dns/templates/netbox_dns/record.html
fixes #250 
To avoid cluttering the UI too much, the 'Tenant' field is not displayed if it is unpopulated.
> Always display tenant for records if defined, not only for unmanaged records

- netbox_dns/models/record.py
- netbox_dns/tests/record/test_validation.py
- netbox_dns/validators/dns_name.py
fixes #256 
This PR introduces stricter validation of domain names as part of values of the following RR types:
* `CNAME`
* `DNAME`
* `HTTPS`
* `KX`
* `MX`
* `NAPTR`
* `NS`
* `NSAP_PTR`
* `NSEC`
* `PTR`
* `PX`
* `RP`
* `RT`
* `SRV`
* `SVCB`
> Introduce stricter validation of domain names as part of record values

- examples/ansible/code/synchronize_dns_zones.yaml
- examples/ansible/using_netbox_dns_with_ansible.md
Hello, as previously mentioned here is a pr to bring the documentation back in line with the Examples. I wasnt sure how to better explain what to do, because the tasks itself  are pretty self explanatory in my view. Maybe you got some suggetions?
I plan on implementing another playbook to generate the needed bind configurations from netbox. (mainly named.conf.local and named.conf.options for Master and Minions) When i got that worked out should do a pr or do you think thats out of scope for this Project?
> Improve Documentation

- netbox_dns/mixins/__init__.py
- netbox_dns/mixins/object_modification.py
- netbox_dns/models/nameserver.py
- netbox_dns/models/record.py
- netbox_dns/models/view.py
- netbox_dns/models/zone.py
fixes #278 
This PR implements a new functionality that helps determining whether anything has changed in a non-saved instance of an object. 
This functionality is then used to determine whether or not to save a record to the database when its `save()` method is called. In some cases, the `save()` method is used to perform actions that don't actually affect the object it is called for, and in these cases saving the object to the database is redundant and should be avoided.
> Avoid saving records when nothing has changed in their values

- netbox_dns/tests/record/test_event_rules.py
- netbox_dns/tests/zone/test_event_rules.py
Fixes #280 
This PR adds tests for the interoperability of NetBox DNS with NetBox after https://github.com/netbox-community/netbox/pull/16366 has been merged. Many of the tests are skipped for NetBox versions < 4.0.4.
> Added tests for the correct handling of event rules

- netbox_dns/__init__.py
- netbox_dns/navigation.py
fixes #295
fixes #296 
This PR aims at making the NetBox DNS entry in the plugin menu more configurable.
1. Optionally register the NetBox DNS menu items under the 'Plugins' top level menu
2. Optionally rename the 'NetBox DNS' menu item if it is not under the 'Plugins' top level menu
Due to the way NetBox integrates plugins, option 1 results in losing section labels 'DNS Configuration', 'Domain Registration' as there is one hierarchy level less available for this. This results in less clarity in the UI.
Both options cannot be used together because NetBox uses the verbose name of the plugin to construct the plugin's section label in the 'Plugins' top level menu. There currently is no way to override this except for changing the plugin's `verbose_name` setting.
Option 1 can be enabled in …
> Made the plugin menu more configurable

- docs/using_netbox_dns.md
- netbox_dns/__init__.py
- netbox_dns/models/record.py
- netbox_dns/models/zone.py
- netbox_dns/tests/nameserver/test_name_validation.py
- netbox_dns/tests/record/test_name_validation.py
- netbox_dns/tests/zone/test_name_validation.py
- netbox_dns/utilities/__init__.py
- netbox_dns/validators/dns_name.py
fixes #299 
This PR adds a new configuration variable, `tolerate_characters_in_zone_labels`, that can be used to enhance the set of characters allowed in zone labels.
The rationale behind this is that [RFC2181, Section 11](https://datatracker.ietf.org/doc/html/rfc2181#section-11) generally allows arbitrary characters in labels, while most DNS server and resolver implementations are much more restrictive. As an example and the immediate reason for this PR,  [RFC2137](https://datatracker.ietf.org/doc/html/rfc2317) uses example zones that contain a slash `/` in their names, which normally isn't permitted by NetBox DNS.
Using slashes in zone names is generally not a very good idea at all, considering the fact that URLs might be constructed using zone names containing `/`, or DNS provisioning …
> Provide an option to allow additional characters in zone labels

- docs/using_netbox_dns.md
fixes #305
The documentation does not specify the `--lazy` option for the reindex command.
If run without that option, the command results in all NetBox search indexes apart from the ones for NetBox DNS to be deleted.
> Fixed the documentation for the `reindex` command

- netbox_dns/tables/nameserver.py
- netbox_dns/tables/record.py
- netbox_dns/tables/zone.py
- netbox_dns/template_content.py
fixes #307 
* Removed a conditional that matches only on NetBox < 3.7, which is not supported
* Removed references to the `pk` column from all tables
> Miscellaneous code cleanup tasks

- netbox_dns/api/serializers_/zone.py
- netbox_dns/tests/zone/test_api.py
fixes #311
The serialisers for the `Zone` objects' `registrant`, `admin_c`, `tech_c` and `billing_c` attributes were missing the `nested=True` setting.
> Fixed serialisers for the `Zone` model

- netbox_dns/forms/record.py
- netbox_dns/forms/view.py
- netbox_dns/forms/zone.py
There were several pieces of old and obsolete code in the forms classes, mainly `APISelect` widgets that were explicitly declared, which became obsolete a while ago.
Fixed some `NullBooleanSelect` fields as well, removing the ugly 'Unknown' placeholder for the null value.
> Cleaned up the forms code

- netbox_dns/models/zone.py
There are two places where a potentially large queryset over objects is used for a list comprehension that delivers only the primary keys for the objects. Replaced this by a construction with `values_list("pk", flat=True)` for efficiency's sake.
> Replaced list comprehension over objects by leaner query for pk

- netbox_dns/tests/custom.py
Due to changed paths in the Strawberry module, some tests for NetBox DNS failed.
> Fixed tests for NetBox 4.0.8 (new Strawberry release)

- netbox_dns/forms/record.py
fixes #337
Commit d4056422f introduced an error in the field type.
> `disable_ptr` must be a `BooleanField` in `RecordForm`

- netbox_dns/mixins/object_modification.py
fixes #341
Apparently `custom_field_data` is not a normal model field. This leads to it being ignored when the list of fields for the `clean_fields` function is first created for a model.
As a result, when only the custom field data for an object is changed, the change may not result in the data being saved.
The solution is to add it to the list of field to check explicitly.
> Check for changed custom fields in `ObjectModificationMixin`

- netbox_dns/tests/record/test_event_rules.py
- netbox_dns/tests/zone/test_event_rules.py
In NetBox 4.1, some input paths and object attributes related to event hooks are changed, and the NetBox version is no longer accessible via `settings.VERSION` but via `utilities.release.load_release_data()`.
As these are (so far) the only places where NetBox 4.1 is incompatible to NetBox 4.0 it should be possible to support the 1.0.x release train of NetBox DNS, which still has IPAM Coupling instead of IPAM AutoDNS, on NetBox 4.1.x This provides a smoother migration path for users relying on IPAM Coupling.
At the same time, NetBox DNS 1.0.x will also be compatible with NetBox 4.0.x, which provides a migration path to IPAM AutoDNS without having to migrate to NetBox 4.1.
tl;dr: No more version dependencies between NetBox 4.x and NetBox DNS 1.x :-)
> Modified event rule tests so they work both with NetBox 4.0.x and 4.1.x

- netbox_dns/filtersets/record.py
Until now, it has only been possible to search for the record name in quick search (global search had the FQDN for a while).
> Enabled searching for records by FQDN in quick search

- netbox_dns/models/zone.py
- netbox_dns/tests/zone/test_rname_validation.py
- netbox_dns/validators/dns_name.py
fixes #355
Allow for escaped dots in an RNAME before the zone part.
> Fixed validation for RNAMEs containing a backslash

- netbox_dns/tables/record.py
Fixed #358
The last PR botched the column name for the `name` column. Noticed this too late :-(
> Fixed the FQDN column name

- netbox_dns/tables/contact.py
- netbox_dns/tables/nameserver.py
- netbox_dns/tables/record.py
- netbox_dns/tables/record_template.py
- netbox_dns/tables/registrar.py
- netbox_dns/tables/view.py
- netbox_dns/tables/zone.py
- netbox_dns/tables/zone_template.py
Many fields in tables that are declared explicitly were also listed in the `fields` array. This is redundant and should be avoided.
> Removed redundant field declarations in tables

- netbox_dns/api/nested_serializers.py
- netbox_dns/api/serializers_/record.py
- netbox_dns/api/views.py
- netbox_dns/tests/nameserver/test_api.py
- netbox_dns/tests/record/test_api.py
- netbox_dns/tests/view/test_api.py
- netbox_dns/tests/zone/test_api.py
fixes #364 
1. Implemented tests (note to self: This should always be the first thing)
2. Replaced `/api/plugins/netbox-dns/views/{view-id}/views/` with `/api/plugins/netbox-dns/views/{view-id}/zones/`
3. Implemented `/api/plugins/netbox-dns/nameservers/{nameserver-id}/soa-zones/`
4. Removed `/api/plugins/netbox-dns/zones/{zone-id}/nameservers/`
5. Modified all endpoints to respect object restrictions (model/object level permissions)
6. Improved the implementation by using related object sets instead of separate queries
7. Replaced the full serializers for the results by the nested variants
8. Added `managed` to `brief_fields` for `Record`
> Fixed multiple REST API issues

- netbox_dns/models/contact.py
- netbox_dns/models/nameserver.py
- netbox_dns/models/record.py
- netbox_dns/models/record_template.py
- netbox_dns/models/registrar.py
- netbox_dns/models/view.py
- netbox_dns/models/zone.py
- netbox_dns/models/zone_template.py
Apart from the casing of the models' verbose names, no changes visible to the end user.
> Minor fixes to the model declarations

- netbox_dns/models/nameserver.py
- netbox_dns/models/record.py
- netbox_dns/models/view.py
- netbox_dns/models/zone.py
- netbox_dns/urls/nameserver.py
- netbox_dns/urls/record.py
- netbox_dns/urls/view.py
- netbox_dns/urls/zone.py
- netbox_dns/views/nameserver.py
- netbox_dns/views/record.py
- netbox_dns/views/view.py
- netbox_dns/views/zone.py
Co-authored-by: 12158973+ThomasADavis@users.noreply.github.com
This PR is based on #371 by @ThomasADavis. 
It adds the option to add tenancy contacts to `View`, `Zone`, `NameServer` and `Record` objects. This is a standard functionality of NetBox that can be used by any model, but it's somewhat hard to figure out how to implement it. After Thomas invested a substantial amount of work in finding out what to do, I just put the missing keystone in and it worked.
> Added the feature to add Contacts to Zone, Record, View and NameServer

- netbox_dns/urls/contact.py
- netbox_dns/urls/nameserver.py
- netbox_dns/urls/record.py
- netbox_dns/urls/record_template.py
- netbox_dns/urls/registrar.py
- netbox_dns/urls/view.py
- netbox_dns/urls/zone.py
- netbox_dns/urls/zone_template.py
- netbox_dns/views/contact.py
- netbox_dns/views/nameserver.py
- netbox_dns/views/record.py
- netbox_dns/views/record_template.py
- netbox_dns/views/registrar.py
- netbox_dns/views/view.py
- netbox_dns/views/zone.py
- netbox_dns/views/zone_template.py
Internal improvement only - saves a couple of hundred lines of code and reduces complexity, which is always good.
> Use get_model_urls to reduce complexity in URL registration

- netbox_dns/graphql/schema.py
> Perform proper authorisation checks on GraphQL queries

- .github/workflows/publish.yml
This replaces the old API token authentication for PyPI publishing.
> Use trusted publisher instead of API token

- netbox_dns/views/record.py
fixes #396
Since ec16edba9f6694c4b33f225a1fe47cc9fa79c1e7 ManagedRecordListView shows all records instead of only the managed ones.
> fix: show managed dns records ManagedRecordListView

- netbox_dns/migrations/0009_rename_contact_registrationcontact.py
The migration that removes the content types for the renamed `Contacts` module must only run if the `ObjectChange` model has been moved to `core`, i.e. in NetBox 4.1.
> Fixed migration for NetBox 4.0

- docs/using_netbox_dns.md
- netbox_dns/__init__.py
- netbox_dns/tests/record/test_name_validation.py
> Added TLSA to the list of record types for which leading underscores are allowed

- netbox_dns/tests/ipam_dnssync/test_ipaddress.py
The custom field for disabling DNSsync creation of address records was working, but there wasn't a test for its functionality. 
This PR adds the test.
> Added test for correct functionylity of the "Disable DNSsync" CF

- netbox_dns/mixins/object_modification.py
- netbox_dns/models/zone.py
Currently the `changed_fields` method makes a DB query in order to get the former state of an object so it's possible to determine which fields have changed.
In preparation to making NetBox DNS compatible with NetBox branching, this kind of request has to be avoided wherever possible. This is true for the described use case, and the solution even provides an improved interface for accessing the former content of object attributes.
> Reduce DB queries

- netbox_dns/graphql/schema.py
After the recent changes there were some unused imports left in the GraphQL schema.
This PR removes the import statements.
> Remove unnecessary imports in the GraphQL schema definitions

- netbox_dns/management/commands/rebuild_dnssync.py
- netbox_dns/utilities/ipam_dnssync.py
fixes #410
This PR turns off optimisations for the `rebuild_dnssec` management command that save much time in the general case, but may lead to an incomplete rebuild if IP address filters for views are in place. This behavior has not been made the default because in many cases it won't be necessary and in the general case it saves a lot of time.
The optimisation simply checks whether the IP address (address, DNS name and the DNSsync CFs) is still consistent with the address records associated with the address, and updating the records only if that's not the case. This does not take the case into account that the inconsistency is caused by a modified IP address filter, though, as checking that case on an individual base is expensive in terms of database operations.
By using the `--force` …
> Add an option to turn off optimisation for rebuild_dnssync

- netbox_dns/models/record.py
- netbox_dns/models/record_template.py
- netbox_dns/tests/record/test_validation.py
- netbox_dns/validators/dns_value.py
fixes #423
* Validate the value for `TXT` and `SPF` records to ensure they are printable ASCII strings.
* If the length of the value for these record types exceeds the maximum allowed by `dnspython`, break it in multiple parts and validate the result again
> Added validation for TXT and SRV record values, and help with adding them to a zone

- netbox_dns/tests/custom.py
- netbox_dns/tests/test_netbox_dns.py
Some GraphQL tests are still failing, but that's probably not something that can be fixed in NetBox DNS. I'll investigate further, but with low priority.
> Made tests more compatible with NetBox 4.0

- docs/using_netbox_dns.md
- netbox_dns/__init__.py
After finding that some of my customers made use of the option to rename the menu to "DNS", I changed the default from "NetBox DNS" to "DNS".
@mjf #296 - admitted, you were right. And to be honest, it **does** look better :-)
> Changed default menu name from "NetBox DNS" to "DNS"

- netbox_dns/models/record.py
- netbox_dns/models/zone.py
- netbox_dns/templates/netbox_dns/record.html
- netbox_dns/views/record.py
fixes #445 
This PR warns when the user creates a record in a parent zone that actually defines a name in a child zone, e.g. if zones `example.com` and `zone1.example.com` exist and a record with the name `name1.zone1` is created in zone `example.com`.
Glue records are exempt from this warning, as they are necessary to avoid infinite lookup loops.
> Added a warning when a record in a zone may be masked from view by a child zone

- netbox_dns/models/record.py
- netbox_dns/models/zone.py
- netbox_dns/views/record.py
fixes #449 
Do not warn when a DS record with the name of a child zone is added to the parent zone. This is a correct and necessary record in the parent zone, not a potential error.
> Do not warn about masking  for DS records in parent zones

- netbox_dns/template_content.py
The first implementation of the new table column lacked the information in which view an address record's zone is located. While the type of the record (`A` vs. `AAAA`) is quite irrelevant as it's determined by the address family of the IP Address, the view information is relevant.
> Improved rendering of the address record links

- netbox_dns/api/views.py
- netbox_dns/forms/record.py
- netbox_dns/forms/view.py
- netbox_dns/models/nameserver.py
- netbox_dns/models/record.py
- netbox_dns/models/record_template.py
- netbox_dns/models/zone.py
- netbox_dns/utilities/ipam_dnssync.py
- netbox_dns/views/nameserver.py
- netbox_dns/views/record.py
- netbox_dns/views/registrar.py
- netbox_dns/views/registration_contact.py
- netbox_dns/views/view.py
- netbox_dns/views/zone.py
Cleaned up some queries by removing redundant `.all()` terms and replaced some queries with variants based on related sets.
This also should have the advantage of playing more smoothly with the branching plugin (just a guess, but I assume that a global query needs some attention to use the current branch while the related object set is assumed to be branch aware.
Even if that's not correct it's less code :-)
> Reduced complexity of some queries

- netbox_dns/__init__.py
fixes #463 
In case of some plugin configuration settings that expect lists, a misconfiguration is only detected at runtime, yielding a "500 Internal Server Error" type exception.
This PR adds basic validation at start time, making NetBox startup fail if there is a misconfigured setting that would lead to such an error.
> Detect misconfigured plugin config lists at start time

- netbox_dns/mixins/object_modification.py
- netbox_dns/tests/record/test_custom_field_changes.py
fixes #472
Changes to custom fields were not detected by `ObjectChangeMixin` because `custom_field_data` only contains a reference to a dictionary and only the reference was saved, not the dictionary itself.
> Fixed change detection for custom fields

- netbox_dns/models/zone.py
> Run delete() for nameserver objects, not a queryset on removal

- netbox_dns/management/commands/rebuild_dnssync.py
Get a list of candidate zones for IP addresses with IPAM DNSsync (use `--verbosity 3`) when running the `rebuild_dnssync` management command.
> Provided slightly more detailed debugging for rebuild_dnssync

- docs/using_netbox_dns.md
You can't actually import status choices in `settings.py`, so the documentation needs to mention the plain status names in examples.
> Fixed the documentation regarding status names in `settings.py`

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
Hello, 
I propose to improve slightly issues templates by using native title tags (## => h2) instead of bold (**), which make templates more standard and accessible. 
Thks you for the job.
> docs(issues): use markdown semantic tag for issues titles

- netbox_dns/signals/ipam_dnssync.py
fixes #488
This PR fixes an issue with the validation of DNS names for IP addresses with DNSsync.
When bulk-importing a duplicate IP address that would violate a uniqueness constraint (either set per prefix or via `ENFORCE_GLOBAL_UNIQUE`), the `post_clean` handler for NetBox DNS is apparently run before the duplicate check in NetBox is executed. This causes NetBox DNS to check for duplicate address records, and even if the DNS name is empty for the duplicate records this will result in an error message stating that there are duplicate records for the IP address.
This is OK if DNS names have actually been set and are the same, but if there are none the error message is erroneous and should not be raised as it covers the real reason for the failed import.
> Check whether dns_name set before running post_clean on IP addresses

- docs/using_netbox_dns.md
- netbox_dns/__init__.py
- netbox_dns/tests/record/test_validation.py
fixes #494 
This is a solution to a concrete problem reported in the issue mentioned above. While probably not the final generic solution, it at least eliminates a problem with a fairly common use case.
> Accept leading underscores in CNAME and DNAME record names

- docs/using_netbox_dns.md
- netbox_dns/__init__.py
- netbox_dns/choices/record.py
- netbox_dns/forms/record.py
- netbox_dns/forms/record_template.py
fixes #521
This PR introduces the `filter_record_types` configuration setting which defines a list of record types to be left out from the selection menus in the GUI.
By default the list is empty. If RR types are listed in the setting's value (which needs to be a list of strings), these types are excluded from the selection when records or record templates are created, updated, filtered etc.
Existing records or records created by the plugin itself are not affected by this filter.
> Added a configuration option to disable the creation of selected record types

- netbox_dns/tests/zone/test_name_validation.py
- netbox_dns/validators/dns_name.py
> Disallow names that can be interpreted as IPv4 addresses (RFC 1912)

- netbox_dns/forms/zone.py
- netbox_dns/tests/zone/test_prefix_notation.py
- netbox_dns/utilities/conversions.py
fixes #525
This PR adds the convenience function to specify zone names for reverse zones by entering a prefix in the 'name' field.
If the prefix is an IPv4 or IPv6 prefix that can be directly mapped to an `in-addr.arpa` or `ip6.arpa` zone, the input will be accepted and converted to the corresponding name.
In all other cases the input is processed verbatim. In particular that means that prefixes like `10.0.0.0/27` and `2001:db8::/45` will **not** be converted, as there is no matching reverse zone name for them.
> Added option to enter reverse zone names as prefix in ZoneForm

- netbox_dns/models/__init__.py
- netbox_dns/templates/netbox_dns/nameserver.html
- netbox_dns/templates/netbox_dns/record.html
- netbox_dns/templates/netbox_dns/recordtemplate.html
- netbox_dns/templates/netbox_dns/view.html
- netbox_dns/templates/netbox_dns/zone.html
- netbox_dns/templates/netbox_dns/zonetemplate.html
This PR contains various cleanups:
* Duplicated "Description" field in `Zone` and `ZoneTemplate` detail views removed
* Rearranged the order of some fields in `Record` detail view to be more logical
* Uniformly only display "Tenant" in detail views when it's actually used (this was only be done for some, not all)
In addition, the deprecated access to `models.Record*Choices` and `models.Zone*Choices` has now been removed. It was deprecated for a while now and originally was scheduled for removal in version 1.1.
> Housekeeping: De-cluttered UI and removed deprecated access to ChoiceSets

- netbox_dns/views/nameserver.py
- netbox_dns/views/record.py
- netbox_dns/views/record_template.py
- netbox_dns/views/registrar.py
- netbox_dns/views/registration_contact.py
- netbox_dns/views/view.py
- netbox_dns/views/zone.py
- netbox_dns/views/zone_template.py
fixes #531 
The `filterset` definition was missing with all `*BulkDeleteView` classes, leading to filters being ignored when the 'Delete all xxx matching yyy' option was used.
> Added FilterSets to all BulkDelete views

- docs/using_netbox_dns.md
Upon scrolling through the (excellent!) documentation of this plugin (I’m looking forward to testing it soon) I stumbled over a few typos.
I also took the liberty of `s/state/version` for the SOA serial number, it it’s not really _state_ which is recorded on the primary, but more of a _version_ number which is compared between secondary and primary.
When SOA REFRESH elapses, a secondary will again query SOA for SERIAL and then decide whether or not to XFR. (When EXPIRE is reached after not being able to contact a primary, the secondary will stop responding to queries for the zone; REFUSED will be returned as rcode)
> typos and a bit of rewording

- netbox_dns/models/nameserver.py
- netbox_dns/models/record.py
- netbox_dns/models/record_template.py
- netbox_dns/models/zone.py
- netbox_dns/tests/nameserver/test_name_validation.py
- netbox_dns/tests/record/test_name_validation.py
- netbox_dns/tests/zone/test_name_validation.py
fixes #547 
This change has been long overdue, thanks to @john2893 for pointing out the problem in #546.
With this change in place, all record, nameserver and zone names will be normalised to all-lowercase letters. This solves the problem described in #546 and the resulting issue, as well as several other potential uniqueness problems with names that may arise from case-sensitive comparisons.
Breaking change: All objects of the classes mentioned above will be modified so their names use lower case letters only on next save.
> Normalise name server, zone and record names to lowercase

- netbox_dns/models/nameserver.py
- netbox_dns/models/zone.py
The standard error messages for violated unique constraints are not very enlightening.
> Provided sensible error messages

- netbox_dns/migrations/0014_alter_unique_constraints_lowercase.py
The error messages added recently were still missing from the migrations.
> Added new error messages to the migrations for ci uniqueness of Nameserver and Zone

- docs/using_netbox_dns.md
- netbox_dns/fields/__init__.py
- netbox_dns/fields/timeperiod.py
- netbox_dns/forms/record.py
- netbox_dns/forms/record_template.py
- netbox_dns/forms/zone.py
Django has (limited) support for ISO 8601 duration values. This PR makes use of what is available to ease the entry of time periods, e.g. for SOA fields. Instead of entering a value like "8640000", it's now possible to enter "P100D" for "100 days".
It should be noted that Django does not support ISO 8601 durations in their entirety. There are other Python libraries that do, but it didn't seem justified to add a new dependency just for a little simplification in the input forms.
> Added a TimePeriod field for ISO 8601 duration entry

- examples/custom-validators/dnssync_perm.py
Small mistake : the custom validator, when tested, would raise an exception :
"dns.exception.SyntaxError: 'IPAddress' object has no attribute 'get'"
Convert IP address to string for the validator to work.
> Update dnssync_perm.py custom validator example

- netbox_dns/tests/custom.py
- netbox_dns/tests/custom/__init__.py
- netbox_dns/tests/custom/netbox.py
- netbox_dns/tests/custom/netbox_dns.py
- netbox_dns/tests/dnssec_key_template/test_api.py
- netbox_dns/tests/dnssec_policy/test_api.py
- netbox_dns/tests/nameserver/test_api.py
- netbox_dns/tests/record/test_api.py
- netbox_dns/tests/record_template/test_api.py
- netbox_dns/tests/registrar/test_api.py
- netbox_dns/tests/registration_contact/test_api.py
- netbox_dns/tests/view/test_api.py
- netbox_dns/tests/zone/test_api.py
- netbox_dns/tests/zone_template/test_api.py
This PR adds a special test for using a NetBox DNS object as a target object in a custom field. The purpose is to catch errors like the one that caused issue #593.
Additionally some obsolete code for NetBox 4.0.x testing was removed.
> Add tests for NetBox DNS objects as custom field targets

- netbox_dns/__init__.py
- netbox_dns/urls.py
fixes #582 
This PR removes an ugly workaround that was implemented so that the `register_model_view()` decorator was executed before using `get_model_urls()` in urls.py.
As it turned out this workaround has some side effects that cause some errors when NetBox is reloaded, among other things the aforementioned bug #582. Loading the views in `urls.py` instead solves those issues.
> Initialise views in `urls.py` instead of `ready()`

- docs/using_netbox_dns.md
- netbox_dns/__init__.py
- netbox_dns/choices/dnssec_key_template.py
- netbox_dns/choices/dnssec_policy.py
- netbox_dns/choices/record.py
- netbox_dns/choices/utilities.py
- netbox_dns/models/record.py
- netbox_dns/validators/dns_value.py
fixes #598
This PR contains a redesign of the choicesets for the `Record` class. Apart from simplifying the setup of the dynamic choice sets and filtering record types it also makes it possible to create custom record types, such as `ALIAS` and `LUA`.
Custom record types will not be validated in any way.
> Redesigned the record ChoiceSets and created the `custom_record_types` option

- docs/using_netbox_dns.md
- netbox_dns/__init__.py
- netbox_dns/choices/record.py
This PR fixes an issue that prevented providing a default value for `filter_record_types` in the plugin configuration and adds a list of record types that are very likely never used, although they are, strictly speaking, RFC compliant.
As a result, the list of record types available in the GUI is much shorter than before, which should make it more convenient to add new records manualls.
In addition, the configuration variable `filter_record_types` was complemented by its cumulative counterpart `filter_record_types+`. If a list of records is specified using the latter variable, it will be added to the types already present in the default list.
Thanks to @jpmens who brought this back to my attention in #541.
> Provide a default list of filtered RRTYPEs

- netbox_dns/models/zone.py
- netbox_dns/tests/zone/test_auto_soa_serial.py
fixes #605
This turned out to be a larger-scale issue - in fact there is a long list of fields that, when updated, must not trigger a SOA update:
* description
* status
* dnssec_policy
* inline_signing
* registrar
* registry_domain_id
* expiration_date
* domain_status
* registrant
* admin_c
* tech_c
* billing_c
* rfc2317_parent_managed
* tenant
This PR fixes it and introduces tests for each of the fields.
> Introduced check for SOA-safe fields and added tests

- netbox_dns/tests/record/test_validation.py
- netbox_dns/validators/dns_name.py
Fixes #613 
This issue uncovered an interesting edge case: 
The detection of invalid double dashes involved checking for a double dash in the third and fourth column after a word boundary. That works for many cases, as the beginning of a label is always a word boundary (beginning of string or '.'), but vice versa a word boundary is not always the beginning of a label.
The example in the issue `2001-e--1.eno1.pve1` has a dash in the fourth column (which constitutes two word boundaries but none is the the beginning of a label), and the first is followed by a substring that has `-e` in the first two columns and `--` in the third and fourth, which is (incorrectly) detected as an invalid double dash.
> Fix detection of invalid double dashes

- netbox_dns/forms/zone.py
- netbox_dns/locale/de/LC_MESSAGES/django.po
- netbox_dns/locale/en/LC_MESSAGES/django.po
- netbox_dns/locale/fr/LC_MESSAGES/django.po
Possibly the last regular update to the 1.2 release tree before 1.3 is released.
There's a minor fix to one of the labels in the Zone form, and an update to a German translation string.
@jean1, if you could have a look at the translation for "Parental Agents" that would be great. If you can't, I'll keep it at the placeholder value I inserted after consulting deepl.com ("Agents Parentaux"), which may or may not be correct ... as I said, my French is absolutely non-existent.
> Updated and fixed translations

- netbox_dns/tables/view.py
- netbox_dns/template_content.py
- netbox_dns/views/dnssec_key_template.py
- netbox_dns/views/record.py
- netbox_dns/views/record_template.py
- netbox_dns/views/zone_template.py
NetBox 4.3 introduced a new feature that makes it possible to re-use table configurations.
As a consequence of this new feature, embedded tables no longer observe the `default_field` settings without being configured on instantiation. This PR does exactly that for all embedded tables used in the plugin.
See https://github.com/netbox-community/netbox/issues/19380 for reference.
> Fix embedded tables

- .github/workflows/lint.yml
Run `ruff` in addition to `black` to ensure no unused imports etc. are missed when checking the quality of the code
> Added ruff to the standard workflow

- netbox_dns/management/commands/remove_orphaned_ptr_records.py
This provides the `remove_orphaned_ptr_records` management command for fixing PTR records left undeleted by the bug reported in #640.
> Added management command for removing orphaned PTR records

- netbox_dns/templates/netbox_dns/record.html
fixes #641 
This PR adds an "Add CNAME" button to all record and managed record detail views except CNAME. While it is technically permissible to have CNAMEs refer to CNAMES, it is not recommended for various reasons and I don't want to make it too easy to create CNAME chains.
> Added an "Add CNAME" button to record and managed record detail views

- examples/custom-scripts/NetBox_DNS_Exporter.py
Setting autoescape = True in jinja2.Environment() leads to converting `"` to `&#34;` when exporting a zone.
> Update NetBox_DNS_Exporter.py set autoescape=False

- netbox-plugin.yaml
- netbox_dns/__init__.py
- netbox_dns/tests/test_netbox_dns.py
- pyproject.toml
Emergency bugfix release as NetBox 4.3.3 breaks deleting IP addresses linked to DNS records, which is a major malfunction.
> Prepared release 1.3.4

- netbox_dns/views/record.py
Currently the "CNAME Targets" and "CNAME" information in the record detail view contains active and inactive records. This change modifies the behaviour to only display active records in both views.
> Modified the CNAME target and CNAME source tables to only display active records

- netbox_dns/forms/dnssec_key_template.py
- netbox_dns/forms/zone.py
- netbox_dns/models/dnssec_key_template.py
- netbox_dns/models/zone.py
- netbox_dns/tests/zone/test_filtersets.py
- netbox_dns/tests/zone/test_views.py
Using the `HTMXSelect` widgets for choice fields in forms makes it possible to modify the forms' field sets so to reduce the complexity of the form.
This PR uses the technique to remove some fields from zone and DNSSEC key template forms.
> Use HTMXSelect to de-clutter the UI for some forms

- netbox-plugin.yaml
- netbox_dns/__init__.py
- netbox_dns/tests/test_netbox_dns.py
- pyproject.toml
This is a minor release, mainly to keep in sync with NetBox minor release 4.4.0.
NetBox 4.3.2 and higher are still supported as the 4.4.0 release did not provide any breaking changes.
> Prepared release 4.4.0

- netbox_dns/tests/dnssec_policy/test_views.py
- netbox_dns/tests/nameserver/test_views.py
- netbox_dns/tests/registrar/test_views.py
- netbox_dns/tests/registration_contact/test_views.py
- netbox_dns/tests/view/test_views.py
- netbox_dns/tests/zone/test_views.py
Check the accessibility of all view tabs for the following models:
* DNSSECPolicy
* NameServer
* Registrar
* RegistrationContact
* View
* Zone
These tests would have detected (among potential other similar issues) the problem reported in #703.
> Implemented accessibility tests for viewtabs of detail views

- netbox_dns/fields/address.py
- netbox_dns/models/zone.py
When a new reverse zone was created or the name, view or status of an existing one was updated, formerly all A and AAAA records that did not have a PTR record were checked for a PTR record in the new or updated zone.
This was a major performance hit and could be - in some cases, drastically - reduced by two measures:
* Check for the IP family of the zone and check only A or only AAAA records without PTR
* Check only records whose "ip_address" field falls into the new zone's "arpa_network" or "rfc2317_prefix".
Especially the second measure should speed up the creation of new reverse zones, especially in environments with many address records.
> Performance improvement when creating or updating reverse zones
