pyproject.toml
Trying to resolve a CodeQL error
=> Updated version string on pytest dependency

docs/using_netbox_dns.md
This PR was taken over from the old repository as it is not likely ever to be merged there.
=> Fixed typos in the documentation

netbox_dns/models.py
=> Fix duplicate zone name validation when no view exists

docs/using_netbox_dns.md, netbox_dns/__init__.py, netbox_dns/models.py, netbox_dns/tests/zone/test_name_validation.py, netbox_dns/utilities.py, netbox_dns/validators.py
=> Enable the management of root zones

netbox_dns/models.py, netbox_dns/tests/zone/test_name_validation.py
=> Do not mistake RFC2317 zones for standard reverse zones

docs/using_netbox_dns.md
=> Fixed typo in validation options documentation

README.md, docs/using_netbox_dns.md
Fixed outdated version requirements in the documentation
=> Fix minimum NetBox version in the documentation

netbox_dns/middleware.py
=> Fixed wrong import in `middleware.py`

netbox_dns/middleware.py, netbox_dns/tests/coupling/test_ip_dns_coupling.py
=> Fixed address record deletion when coupling fields are cleared

netbox_dns/forms/record.py
=> Added missing "type" attribute to the record filter

netbox_dns/urls.py
Adds Journal for Record, Zone, Registrar and Contact models.  Fixes [#121](https://github.com/peteeckel/netbox-plugin-dns/issues/121).
=> Add journal tab

netbox_dns/templates/netbox_dns/record.html, netbox_dns/templates/netbox_dns/record/related.html
This only cleans up some optical quirks in the UI
=> Some cosmetic changes to the NetBox DNS templates

netbox_dns/__init__.py
closes #138
* Some required CFs were missing from the list of CFs to check
* manage.py createstatic fails when there is no database connection
=> Fixed the ready() method in init.py

netbox_dns/models/record.py, netbox_dns/models/zone.py, netbox_dns/tests/rfc2317/test_records.py
=> Defer RFC2317 CNAME creation until all PTR records have been moved

.github/workflows/test.yml, netbox_dns/signals/ipam_coupling.py
=> Properly report a CNAME conflict with IPAM coupling

netbox_dns/utilities/__init__.py
=> No longer rely on netaddr.IPNetwork partial IPv4 network completion

netbox_dns/forms/zone.py, netbox_dns/tests/zone/test_views.py
=> Added nameservers to the bulk importable files for Zone

netbox_dns/management/commands/cleanup_database.py, netbox_dns/models/record.py, netbox_dns/models/zone.py
=> Removed double save() for address records with PTR records

netbox_dns/models/record.py, netbox_dns/tests/record/test_enforce_unique.py
=> Fix duplicate record check for `enforce_unique_records`

netbox_dns/api/serializers.py, netbox_dns/filters/registrar.py, netbox_dns/forms/registrar.py, netbox_dns/templates/netbox_dns/registrar.html
=> Added the address field to registrar views

docs/using_netbox_dns.md, netbox_dns/__init__.py, netbox_dns/management/commands/cleanup_rrset_ttl.py, netbox_dns/models/record.py, netbox_dns/tests/record/test_uniqueness.py
=> Ensure unique TTL for RRSets

docs/using_netbox_dns.md
Two actions are missing in the installation section:  You have to enable the plugin first and at least restart netbox service too.
=> Update documentation using_netbox_dns.md

netbox_dns/views/record.py
=> Fixed domain search list for CNAME targets and CNAMEs

netbox_dns/filters/record.py, netbox_dns/filters/zone.py, netbox_dns/forms/record.py, netbox_dns/forms/zone.py
=> Allow multiple selections in the Zone status and Record type and status filters

netbox_dns/forms/registrar.py, netbox_dns/tests/contact/test_views.py, netbox_dns/tests/nameserver/test_views.py, netbox_dns/tests/record/test_views.py, netbox_dns/tests/registrar/test_views.py, netbox_dns/tests/view/test_views.py, netbox_dns/tests/zone/test_views.py
Backport some of the more crucial fixes from feature/netbox-4, especially tests and fixes for the Registrar bulk edit form
=> Backport tests from the NetBox 4 compatibility branch

netbox_dns/forms/zone.py
=> Enabled leaving "RFC2317 Parent Managed" untouched in bulk edit

netbox_dns/api/serializers.py, netbox_dns/filters/record.py, netbox_dns/forms/record.py, netbox_dns/migrations/0003_record_fqdn.py, netbox_dns/models/record.py, netbox_dns/models/zone.py, netbox_dns/tests/record/test_api.py, netbox_dns/tests/record/test_filters.py, netbox_dns/tests/record/test_fqdn.py, netbox_dns/tests/record/test_views.py
=> New Feature: FQDN Filtering

netbox_dns/management/commands/cleanup_rrset_ttl.py
=> Fixed typo in management command "cleanup_rrset_ttl"

netbox_dns/views/record.py
Given the new `fqdn` field for records, the `get_value_record()` function can be simplified and its performance improved.
=> Improved get_value_record() based on the new fqdn field

netbox_dns/__init__.py, netbox_dns/tests/test_netbox_dns.py, pyproject.toml
FInal changes to version 0.22.9 before feature/netbox-4 is merged into main. The legacy branch will host further bugfixes to the 0.22 release compatible with NetBox 3.5+.
=> Prepared release 0.22.9

netbox_dns/models/record.py, netbox_dns/tests/record/test_validation.py, netbox_dns/validators/dns_name.py
=> Allow @ as value for CNAME records

netbox_dns/forms/zone.py, netbox_dns/tables/view.py, netbox_dns/templates/netbox_dns/record.html
=> Minor UI cleanup actions for consistency

examples/ansible/code/generate_bind_config.yaml, examples/ansible/code/named.conf.local.j2, examples/ansible/code/synchronize_dns_zones.yaml, examples/ansible/using_netbox_dns_with_ansible.md
Hello again,
here is a shorted example for a named.conf.local file-generation. I havent implemented views, because i think that is a more individual setup and not suited for a example.
=> Add Ansible named.conf.local generation example

netbox_dns/tables/view.py
=> Made default_view a boolean column in the view table

netbox_dns/models/record.py, netbox_dns/tests/record/test_fqdn.py
=> Fixed `__str__` for unsaved Record objects

netbox_dns/tests/record/test_validation.py, netbox_dns/validators/dns_name.py
=> Added leading underscores in all labels to valid domain name patterns

netbox_dns/models/zone.py, netbox_dns/templates/netbox_dns/zone.html, netbox_dns/templates/netbox_dns/zone/child_zone.html, netbox_dns/tests/zone/test_parent_child.py, netbox_dns/urls/zone.py, netbox_dns/views/zone.py
=> Implemented Parent/Child information in the Zone detail view

netbox_dns/templates/netbox_dns/zone.html
=> Fixed manually coded "linkify" in Zone template

netbox_dns/templates/netbox_dns/zone.html
=> Fixed rendering for the RFC2317 card in the Zone detail view

netbox_dns/graphql/types.py
=> Fixed the `nameservers` representation in the GraphQL type for `Zone`

netbox_dns/api/views.py, netbox_dns/tests/record/test_api.py
fixes #308 
* Added code to inhibit creating managed records or setting records to managed via the REST API
* Created tests for these operations
=> Refuse to create managed records or set records to managed via the REST API

netbox_dns/tests/zone/test_api.py, netbox_dns/tests/zone/test_views.py
Zone API and view tests were lacking the nameserver relation.
=> Added namserver tests for zone view and API

netbox_dns/forms/record.py, netbox_dns/forms/zone.py, netbox_dns/models/record.py, netbox_dns/models/view.py, netbox_dns/models/zone.py, netbox_dns/tables/record.py, netbox_dns/template_content.py, netbox_dns/tests/custom.py, netbox_dns/tests/record/test_event_rules.py, netbox_dns/tests/record/test_validation.py, netbox_dns/tests/zone/test_auto_soa_serial.py, netbox_dns/tests/zone/test_default_view.py, netbox_dns/tests/zone/test_event_rules.py, netbox_dns/tests/zone/test_name_validation.py, netbox_dns/tests/zone/test_parent_child.py, netbox_dns/validators/dns_name.py
While not aiming for full pylint conformance, some of the issues raised by the tool are valid and fixing them makes sense, especially unused imports and variables.
=> Fixed some code style issues raised by pylint

netbox_dns/forms/zone.py
=> Made "Tenant" nullable in zone bulk edit forms

netbox_dns/models/zone.py
=> Made soa_serial_dirty an object method for Zone

netbox_dns/api/serializers_/nameserver.py, netbox_dns/api/serializers_/record.py, netbox_dns/api/serializers_/record_template.py, netbox_dns/api/serializers_/zone.py, netbox_dns/models/record_template.py
Modified imports within the same module (e.g. serializers, models) to be relative instead of absolute.
=> Simplified import statements

netbox_dns/forms/zone.py
=> Fixed filtering of zones by nameserver in the GUI

netbox_dns/forms/nameserver.py
=> Implemented filtering nameservers by zone and SOA zone

netbox_dns/forms/zone.py
=> Do not overwrite the contents of SOA SERIAL in ZoneForm

netbox_dns/forms/zone.py
=> Properly handle custom field data when validating zone views

netbox_dns/tables/record.py
=> Added FQDN to the record table column options

netbox_dns/tables/record.py
=> Added view to the record tables

netbox-plugin.yaml, netbox_dns/tests/record/test_api.py, netbox_dns/tests/zone/test_api.py
This release fixes some tests that fail with NetBox 4.0.11 and updates the compatibility matrix.
No changes to functionality or UI.
=> NetBox 4.0.11 adjustments

netbox-plugin.yaml, netbox_dns/__init__.py, netbox_dns/tests/test_netbox_dns.py, pyproject.toml
=> Release 1.1.0

netbox_dns/tests/ipam_dnssync/test_ipaddress.py, netbox_dns/utilities/ipam_dnssync.py
=> Allow empty host label for DNSsync

netbox_dns/migrations/0009_rename_contact_registrationcontact.py
fixes #385
* Workaround for  https://github.com/netbox-community/netbox/issues/17361
=> Clean up orphaned object changes for the renamed Contact model

README.md, docs/using_netbox_dns.md
Added warning not to use NetBox DNS with NetBox Branching
=> Documentation: Added warning for NetBox Branching

netbox_dns/tables/record.py
=> Removed logging code from the record table module

netbox_dns/forms/view.py, netbox_dns/mixins/object_modification.py, netbox_dns/models/record.py, netbox_dns/models/zone.py, netbox_dns/signals/ipam_dnssync.py, netbox_dns/utilities/ipam_dnssync.py
For reference, see NetBox issue https://github.com/netbox-community/netbox/issues/17577 and PR https://github.com/netbox-community/netbox/pull/17583
This is a change aiming to move closer to full support for NetBox branching. It should not have any functional implications.
=> Refer to ModelState to find whether an object is being changed

docs/using_netbox_dns.md
Fixes #420 
Documentation has been added. 
As for tests it turns out that the `@override_settings` decorator cannot be used for this kind of test, which is unfortunate as that way e.g. changes done via `FIELD_CHOICES` can't be tested.
=> Added documentation for Zone/Record status customisation

netbox_dns/filtersets/record.py, netbox_dns/forms/record.py, netbox_dns/forms/zone.py, netbox_dns/locale/de/LC_MESSAGES/django.po, netbox_dns/locale/en/LC_MESSAGES/django.po, netbox_dns/tests/record/test_filtersets.py
=> Added filter for Zone and Record "active" status

netbox_dns/templates/netbox_dns/record.html, netbox_dns/utilities/__init__.py, netbox_dns/utilities/dns.py, netbox_dns/utilities/ipam_dnssync.py, netbox_dns/views/record.py
=> Added a warning when a CNAME value should be in NetBox DNS but is not

netbox_dns/views/record.py
=> Only check for active zones for a CNAME value warning

README.md
Added explicit acknowledgment for the awesome Black code formatting tool.
=> Added Black codestyle badge

examples/custom-scripts/NetBox_DNS_Exporter.py
=> Removed reference to ACTIVE_STATUS_LIST for zones and records

docs/using_netbox_dns.md, netbox_dns/forms/record.py, netbox_dns/forms/zone.py, netbox_dns/forms/zone_template.py
fixes #453
This PR mainly contains improvements to error messages, help texts and documentation for bulk import operations, most notably record imports.
=> Clarify record import

netbox_dns/template_content.py
=> Added a column for DNS address records to the IP address table

netbox_dns/models/record.py
=> Convert ip_address to a netaddr.IPAddress object before checking for changes

netbox_dns/models/record.py
=> Fixed logic for updating zone SOA SERIAL on record save()

netbox-plugin.yaml, netbox_dns/tests/record/test_validation.py, netbox_dns/validators/dns_value.py
=> Allow tolerating non-RFC1035 names in RR values

docs/using_netbox_dns.md, netbox_dns/__init__.py
=> Allow SVCB records to contain underscores in the name

netbox_dns/api/serializers_/record.py, netbox_dns/graphql/types.py, netbox_dns/models/record.py, netbox_dns/tests/record/test_absolute_value.py
=> Add an `absolute_value` attribute to the `Record` model

netbox_dns/templates/netbox_dns/zone.html, netbox_dns/templatetags/netbox_dns.py
=> Added the date/time equivalent to auto-generated SOA SERIALs in zone detail view

examples/custom-validators/dnssync_perm.py
Just some minor cleanup after ruff complained.
=> Cleaned up imports after ruff check

docs/using_netbox_dns.md
=> Use primary/secondary consistently

netbox_dns/tests/record/test_event_rules.py, netbox_dns/tests/zone/test_event_rules.py
There still was code for specific features on NetBox < 4.2 in some of the test modules. This code is no longer applicable and was removed.
=> Removed version specific code for NetBox < 4.1 from tests

netbox_dns/tests/record/test_validation.py
This PR fixes a slight incompatibility with the latest Black release.
=> Adjustment for the latest Black release

examples/custom-scripts/using_custom_scripts.md
@kollross published some useful tools for NetBox and NetBox DNS that make a useful addition to the code examples. Added a link to the GitHub repo.
=> Added a link to @kollross' GitHub repo to the examples doc

docs/using_netbox_dns.md
as discussed in https://github.com/peteeckel/netbox-plugin-dns/pull/578
(and I removed two spaces at end of line)
=> add DNS server options table to documentation

netbox_dns/forms/zone.py
=> SOA MNAME must be checked in zone forms if zone template is not set

netbox-plugin.yaml, netbox_dns/__init__.py, netbox_dns/tests/test_netbox_dns.py, pyproject.toml
This PR contains the DNSSEC feature set as a major enhancement, as well as some minor enhancements and fixes.
=> Prepared release 1.2.7

netbox_dns/models/zone.py
=> Declared parental_agents a SOA clean field

netbox_dns/api/serializers_/dnssec_key_template.py, netbox_dns/api/serializers_/dnssec_policy.py, netbox_dns/api/serializers_/nameserver.py
=> Set the tenant serialiser to nested everywhere it is used

netbox_dns/tests/record/test_views.py, netbox_dns/views/record.py
=> Fix incorrect mask warning

netbox_dns/models/record.py, netbox_dns/models/zone.py
fixes #625
This PR adds a fix to a symptom for a more general issue that won't be fixed in 1.2.x. See the related issue for an explanation.
=> Fix glue record ptr server error

netbox_dns/tables/record.py
=> Fixed the links of entries in the "Address Records" column

netbox-plugin.yaml, netbox_dns/__init__.py, netbox_dns/tests/test_netbox_dns.py, pyproject.toml
Prepared release 1.2.12.
This is a bugfix release fixing #622 and #624 (the latter is fixed only with respect to its symptom, the cause will be fixed in release 1.3.1 for NetBox 4.3.x).
=> Prepared release 1.2.12

netbox_dns/models/record.py, netbox_dns/tests/record/test_auto_ptr.py
While working on the fix for #625 it turned out to be really difficult to understand my own code in `update_ptr_record()`. 
This PR reorganises the code and adds a number of comments that make it easier to understand for myself and others brave enough to work on it.
=> Housekeeping: Code cleanup

netbox_dns/models/record.py
After reviewing the last changes it turned out that the code can be even simpler. Simpler is better.
=> Simplified update_ptr_record() further

netbox_dns/templates/netbox_dns/zone/base.html
=> Return to the zone record list after adding a record with the "Add Record" button

netbox-plugin.yaml, pyproject.toml
Minor fix to `pyproject.toml` and updated version matrix.
=> Housekeeping: Metadata cleanup

netbox_dns/models/zone_template.py
=> Clone SOA MName and SOA RName for zone templates

netbox_dns/models/record.py, netbox_dns/tests/ipam_dnssync/test_ipaddress.py
=> Fix IPAM DNSsync server error on change of "DNS Name"

netbox-plugin.yaml, netbox_dns/__init__.py, netbox_dns/tests/test_netbox_dns.py, pyproject.toml
=> Prepared release 1.3.5

netbox_dns/management/commands/cleanup_database.py
=> Fixed verbose messages for orphaned record cleanup (f-string)

netbox_dns/management/commands/rebuild_dnssync.py, netbox_dns/tests/ipam_dnssync/test_ipaddress.py, netbox_dns/tests/management_commands/test_rebuild_dnssync.py, netbox_dns/utilities/ipam_dnssync.py
=> Fix CF based view filters not being observed when an address record needs to be removed

README.md, netbox-plugin.yaml, netbox_dns/__init__.py, netbox_dns/tests/test_netbox_dns.py, pyproject.toml
=> Prepared release 1.4.1
